services:
  - type: web
    name: ifc-api
    runtime: python
    buildCommand: ""
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHONUNBUFFERED
        value: true
